spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
        use_sql_comments: true

  profiles:
    include: key

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

naver:
  key: asdf