spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
#        default_batch_fetch_size: 1000
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:13306/flywaytest?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  profiles:
    include: key

  flyway:
    baseline-on-migrate: true
    baseline-version: 0

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

naver:
  key: asdf

person:
  name: defaultBepoz
  age: 100